### ISSUE TITLE
Spridd feedback!

### ISSUE THREAD

**Issue by consideRatio** [kevindeeboman/masters_project#1]
Hej!

Jag har råkat hamna här lite av en slump, men tänkte ge lite korta tips out of the blue, hoppas det känns okej!

- [x] Länka er presentation om detta projekt som jag såg på https://www.youtube.com/watch?v=sfWWPpTysjk&t=51m i erat projekts README fil. Det gav en bra intro till projektet!
- [x] Skapa en requirements.txt eller liknande fil som klargör vilka python dependencies ni har använt er av.
- [x] Skapa en länk till mybinder.org motsvarande följande exempellänk: https://mybinder.org/v2/gh/jupyterlab/jupyterlab-demo/master?urlpath=lab/tree/demo
  
  De som klickar på den får en tempporär Jupyter server startad åt sig innehållande github repot som beskrivs i länken som dessutom också får requirements.txt dependencies och liknande installerade automatiskt.
  
Varma hälsningar från Uppsala!

**Comment by kevindeeboman** [comment]
Hej!

Tack så jättemycket för att du tog dig tiden att ge feedback. Jag har har nu implementerat dina förslag, om du ser något annat så uppskattas all respons.

Hälsningar från ett soligt Göteborg!

**Comment by consideRatio** [comment]
Bara roligt med så positiv respons :) Wow det gick undan!

Ha en fin dag!
